//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiron.LojaVirtual.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRegistro
    {
        public int Idlog { get; set; }
        public string login { get; set; }
        public string nameUser { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> dateReg { get; set; }
    }
}
